# Generated by Django 3.2.9 on 2021-12-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='image_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bag',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='bag',
            name='promotion',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
